//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEmulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int OrderStatusId { get; set; }
        public int DepartmentId { get; set; }
        public string UID { get; set; }
        public int Number { get; set; }
        public string TableNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string RoomNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public int SpentTime { get; set; }
        public string Waiter { get; set; }
        public int QueueStatusId { get; set; }
        public int LanguageTypeId { get; set; }
    
        public virtual LanguageType LanguageType { get; set; }
        public virtual QueueStatu QueueStatu { get; set; }
    }
}
