//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingEmulator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KDS_06_10Entities : DbContext
    {
        public KDS_06_10Entities()
            : base("name=KDS_06_10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LanguageTypes> LanguageTypes { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<QueueStatus> QueueStatus { get; set; }
    }
}
