//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookPhase
    {
        public int Id { get; set; }
        public int OrderDishId { get; set; }
        public int CookPhaseTypeId { get; set; }
        public bool IsActive { get; set; }
        public int SpanTime { get; set; }
    
        public virtual CookPhaseType CookPhaseType { get; set; }
        public virtual OrderDish OrderDish { get; set; }
    }
}
