//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContextKDS : DbContext
    {
        public DBContextKDS()
            : base("name=DBContextKDS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CookPhase> CookPhase { get; set; }
        public virtual DbSet<CookPhaseType> CookPhaseType { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartmentDepartmentGroup> DepartmentDepartmentGroup { get; set; }
        public virtual DbSet<DepartmentGroup> DepartmentGroup { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDish> OrderDish { get; set; }
    }
}
