//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSService.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDish
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> DishStatusId { get; set; }
        public int DepartmentId { get; set; }
        public string UID { get; set; }
        public string DishName { get; set; }
        public int FilingNumber { get; set; }
        public decimal Quantity { get; set; }
        public string ParentUid { get; set; }
        public int EstimatedTime { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int SpentTime { get; set; }
        public bool IsRollback { get; set; }
        public Nullable<System.DateTime> RollbackDate { get; set; }
        public int ReadySpentTime { get; set; }
        public string UID1C { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Order Order { get; set; }
    }
}
