//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKDSService")]
    public interface IKDSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetOrders", ReplyAction="http://tempuri.org/IKDSService/GetOrdersResponse")]
        KDSService.AppModel.Order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetOrders", ReplyAction="http://tempuri.org/IKDSService/GetOrdersResponse")]
        System.Threading.Tasks.Task<KDSService.AppModel.Order[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/ChangeOrderStatus", ReplyAction="http://tempuri.org/IKDSService/ChangeOrderStatusResponse")]
        void ChangeOrderStatus(KDSService.OrderCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/ChangeOrderStatus", ReplyAction="http://tempuri.org/IKDSService/ChangeOrderStatusResponse")]
        System.Threading.Tasks.Task ChangeOrderStatusAsync(KDSService.OrderCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKDSServiceChannel : KDSConsoleClient.ServiceReference1.IKDSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KDSServiceClient : System.ServiceModel.ClientBase<KDSConsoleClient.ServiceReference1.IKDSService>, KDSConsoleClient.ServiceReference1.IKDSService {
        
        public KDSServiceClient() {
        }
        
        public KDSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KDSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KDSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KDSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KDSService.AppModel.Order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<KDSService.AppModel.Order[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public void ChangeOrderStatus(KDSService.OrderCommand command) {
            base.Channel.ChangeOrderStatus(command);
        }
        
        public System.Threading.Tasks.Task ChangeOrderStatusAsync(KDSService.OrderCommand command) {
            return base.Channel.ChangeOrderStatusAsync(command);
        }
    }
}
