//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSWPFClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    using View;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatusModel", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    [System.SerializableAttribute()]
    public partial class OrderStatusModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName {
            get {
                return this.AppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNameField, value) != true)) {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentModel", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    [System.SerializableAttribute()]
    public partial class DepartmentModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DishQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DishQuantity {
            get {
                return this.DishQuantityField;
            }
            set {
                if ((this.DishQuantityField.Equals(value) != true)) {
                    this.DishQuantityField = value;
                    this.RaisePropertyChanged("DishQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoStart {
            get {
                return this.IsAutoStartField;
            }
            set {
                if ((this.IsAutoStartField.Equals(value) != true)) {
                    this.IsAutoStartField = value;
                    this.RaisePropertyChanged("IsAutoStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientDataFilter", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    [System.SerializableAttribute()]
    public partial class ClientDataFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApproxMaxDishesCountOnPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> DepIDsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndpointOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndpointOrderItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KDSWPFClient.ServiceReference1.OrderGroupEnum GroupByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDishGroupAndSumQuatityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KDSWPFClient.ServiceReference1.LeafDirectionEnum LeafDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> StatusesListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApproxMaxDishesCountOnPage {
            get {
                return this.ApproxMaxDishesCountOnPageField;
            }
            set {
                if ((this.ApproxMaxDishesCountOnPageField.Equals(value) != true)) {
                    this.ApproxMaxDishesCountOnPageField = value;
                    this.RaisePropertyChanged("ApproxMaxDishesCountOnPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> DepIDsList {
            get {
                return this.DepIDsListField;
            }
            set {
                if ((object.ReferenceEquals(this.DepIDsListField, value) != true)) {
                    this.DepIDsListField = value;
                    this.RaisePropertyChanged("DepIDsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndpointOrderID {
            get {
                return this.EndpointOrderIDField;
            }
            set {
                if ((this.EndpointOrderIDField.Equals(value) != true)) {
                    this.EndpointOrderIDField = value;
                    this.RaisePropertyChanged("EndpointOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndpointOrderItemID {
            get {
                return this.EndpointOrderItemIDField;
            }
            set {
                if ((this.EndpointOrderItemIDField.Equals(value) != true)) {
                    this.EndpointOrderItemIDField = value;
                    this.RaisePropertyChanged("EndpointOrderItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KDSWPFClient.ServiceReference1.OrderGroupEnum GroupBy {
            get {
                return this.GroupByField;
            }
            set {
                if ((this.GroupByField.Equals(value) != true)) {
                    this.GroupByField = value;
                    this.RaisePropertyChanged("GroupBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDishGroupAndSumQuatity {
            get {
                return this.IsDishGroupAndSumQuatityField;
            }
            set {
                if ((this.IsDishGroupAndSumQuatityField.Equals(value) != true)) {
                    this.IsDishGroupAndSumQuatityField = value;
                    this.RaisePropertyChanged("IsDishGroupAndSumQuatity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KDSWPFClient.ServiceReference1.LeafDirectionEnum LeafDirection {
            get {
                return this.LeafDirectionField;
            }
            set {
                if ((this.LeafDirectionField.Equals(value) != true)) {
                    this.LeafDirectionField = value;
                    this.RaisePropertyChanged("LeafDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> StatusesList {
            get {
                return this.StatusesListField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusesListField, value) != true)) {
                    this.StatusesListField = value;
                    this.RaisePropertyChanged("StatusesList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderGroupEnum", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    public enum OrderGroupEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByCreateTime = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByOrderNumber = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeafDirectionEnum", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    public enum LeafDirectionEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoLeaf = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Forward = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Backward = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponce", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    [System.SerializableAttribute()]
    public partial class ServiceResponce : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewOrderIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<KDSWPFClient.ServiceReference1.OrderModel> OrdersListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isExistsNextOrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isExistsPrevOrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewOrderIds {
            get {
                return this.NewOrderIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.NewOrderIdsField, value) != true)) {
                    this.NewOrderIdsField = value;
                    this.RaisePropertyChanged("NewOrderIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<KDSWPFClient.ServiceReference1.OrderModel> OrdersList {
            get {
                return this.OrdersListField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersListField, value) != true)) {
                    this.OrdersListField = value;
                    this.RaisePropertyChanged("OrdersList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceErrorMessage {
            get {
                return this.ServiceErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceErrorMessageField, value) != true)) {
                    this.ServiceErrorMessageField = value;
                    this.RaisePropertyChanged("ServiceErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isExistsNextOrders {
            get {
                return this.isExistsNextOrdersField;
            }
            set {
                if ((this.isExistsNextOrdersField.Equals(value) != true)) {
                    this.isExistsNextOrdersField = value;
                    this.RaisePropertyChanged("isExistsNextOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isExistsPrevOrders {
            get {
                return this.isExistsPrevOrdersField;
            }
            set {
                if ((this.isExistsPrevOrdersField.Equals(value) != true)) {
                    this.isExistsPrevOrdersField = value;
                    this.RaisePropertyChanged("isExistsPrevOrders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderModel", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    [System.SerializableAttribute()]
    public partial class OrderModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged, IContainIDField
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, KDSWPFClient.ServiceReference1.OrderDishModel> DishesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionColorRGBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaiterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaitingTimerStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, KDSWPFClient.ServiceReference1.OrderDishModel> Dishes {
            get {
                return this.DishesField;
            }
            set {
                if ((object.ReferenceEquals(this.DishesField, value) != true)) {
                    this.DishesField = value;
                    this.RaisePropertyChanged("Dishes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionColorRGB {
            get {
                return this.DivisionColorRGBField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionColorRGBField, value) != true)) {
                    this.DivisionColorRGBField = value;
                    this.RaisePropertyChanged("DivisionColorRGB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HallName {
            get {
                return this.HallNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HallNameField, value) != true)) {
                    this.HallNameField = value;
                    this.RaisePropertyChanged("HallName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatusId {
            get {
                return this.OrderStatusIdField;
            }
            set {
                if ((this.OrderStatusIdField.Equals(value) != true)) {
                    this.OrderStatusIdField = value;
                    this.RaisePropertyChanged("OrderStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uid {
            get {
                return this.UidField;
            }
            set {
                if ((object.ReferenceEquals(this.UidField, value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Waiter {
            get {
                return this.WaiterField;
            }
            set {
                if ((object.ReferenceEquals(this.WaiterField, value) != true)) {
                    this.WaiterField = value;
                    this.RaisePropertyChanged("Waiter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WaitingTimerString {
            get {
                return this.WaitingTimerStringField;
            }
            set {
                if ((object.ReferenceEquals(this.WaitingTimerStringField, value) != true)) {
                    this.WaitingTimerStringField = value;
                    this.RaisePropertyChanged("WaitingTimerString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDishModel", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    [System.SerializableAttribute()]
    public partial class OrderDishModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged, IContainIDField
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DelayedStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DishStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UID1CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaitingTimerStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DelayedStartTime {
            get {
                return this.DelayedStartTimeField;
            }
            set {
                if ((this.DelayedStartTimeField.Equals(value) != true)) {
                    this.DelayedStartTimeField = value;
                    this.RaisePropertyChanged("DelayedStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DishStatusId {
            get {
                return this.DishStatusIdField;
            }
            set {
                if ((this.DishStatusIdField.Equals(value) != true)) {
                    this.DishStatusIdField = value;
                    this.RaisePropertyChanged("DishStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedTime {
            get {
                return this.EstimatedTimeField;
            }
            set {
                if ((this.EstimatedTimeField.Equals(value) != true)) {
                    this.EstimatedTimeField = value;
                    this.RaisePropertyChanged("EstimatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilingNumber {
            get {
                return this.FilingNumberField;
            }
            set {
                if ((this.FilingNumberField.Equals(value) != true)) {
                    this.FilingNumberField = value;
                    this.RaisePropertyChanged("FilingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentUid {
            get {
                return this.ParentUidField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentUidField, value) != true)) {
                    this.ParentUidField = value;
                    this.RaisePropertyChanged("ParentUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceErrorMessage {
            get {
                return this.ServiceErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceErrorMessageField, value) != true)) {
                    this.ServiceErrorMessageField = value;
                    this.RaisePropertyChanged("ServiceErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID1C {
            get {
                return this.UID1CField;
            }
            set {
                if ((object.ReferenceEquals(this.UID1CField, value) != true)) {
                    this.UID1CField = value;
                    this.RaisePropertyChanged("UID1C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uid {
            get {
                return this.UidField;
            }
            set {
                if ((object.ReferenceEquals(this.UidField, value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WaitingTimerString {
            get {
                return this.WaitingTimerStringField;
            }
            set {
                if ((object.ReferenceEquals(this.WaitingTimerStringField, value) != true)) {
                    this.WaitingTimerStringField = value;
                    this.RaisePropertyChanged("WaitingTimerString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/KDSService.AppModel")]
    public enum OrderStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingCook = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cooking = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ready = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Took = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Commit = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelConfirmed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transferred = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadyConfirmed = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YesterdayNotTook = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKDSService")]
    public interface IKDSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetOrderStatuses", ReplyAction="http://tempuri.org/IKDSService/GetOrderStatusesResponse")]
        System.Collections.Generic.List<KDSWPFClient.ServiceReference1.OrderStatusModel> GetOrderStatuses(string machineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetOrderStatuses", ReplyAction="http://tempuri.org/IKDSService/GetOrderStatusesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KDSWPFClient.ServiceReference1.OrderStatusModel>> GetOrderStatusesAsync(string machineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetDepartments", ReplyAction="http://tempuri.org/IKDSService/GetDepartmentsResponse")]
        System.Collections.Generic.List<KDSWPFClient.ServiceReference1.DepartmentModel> GetDepartments(string machineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetDepartments", ReplyAction="http://tempuri.org/IKDSService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KDSWPFClient.ServiceReference1.DepartmentModel>> GetDepartmentsAsync(string machineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetOrders", ReplyAction="http://tempuri.org/IKDSService/GetOrdersResponse")]
        KDSWPFClient.ServiceReference1.ServiceResponce GetOrders(string machineName, KDSWPFClient.ServiceReference1.ClientDataFilter clientFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetOrders", ReplyAction="http://tempuri.org/IKDSService/GetOrdersResponse")]
        System.Threading.Tasks.Task<KDSWPFClient.ServiceReference1.ServiceResponce> GetOrdersAsync(string machineName, KDSWPFClient.ServiceReference1.ClientDataFilter clientFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetHostAppSettings", ReplyAction="http://tempuri.org/IKDSService/GetHostAppSettingsResponse")]
        System.Collections.Generic.Dictionary<string, object> GetHostAppSettings(string machineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/GetHostAppSettings", ReplyAction="http://tempuri.org/IKDSService/GetHostAppSettingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetHostAppSettingsAsync(string machineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/SetExpectedTakeValue", ReplyAction="http://tempuri.org/IKDSService/SetExpectedTakeValueResponse")]
        void SetExpectedTakeValue(string machineName, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSService/SetExpectedTakeValue", ReplyAction="http://tempuri.org/IKDSService/SetExpectedTakeValueResponse")]
        System.Threading.Tasks.Task SetExpectedTakeValueAsync(string machineName, int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKDSServiceChannel : KDSWPFClient.ServiceReference1.IKDSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KDSServiceClient : System.ServiceModel.ClientBase<KDSWPFClient.ServiceReference1.IKDSService>, KDSWPFClient.ServiceReference1.IKDSService {
        
        public KDSServiceClient() {
        }
        
        public KDSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KDSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KDSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KDSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KDSWPFClient.ServiceReference1.OrderStatusModel> GetOrderStatuses(string machineName) {
            return base.Channel.GetOrderStatuses(machineName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KDSWPFClient.ServiceReference1.OrderStatusModel>> GetOrderStatusesAsync(string machineName) {
            return base.Channel.GetOrderStatusesAsync(machineName);
        }
        
        public System.Collections.Generic.List<KDSWPFClient.ServiceReference1.DepartmentModel> GetDepartments(string machineName) {
            return base.Channel.GetDepartments(machineName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KDSWPFClient.ServiceReference1.DepartmentModel>> GetDepartmentsAsync(string machineName) {
            return base.Channel.GetDepartmentsAsync(machineName);
        }
        
        public KDSWPFClient.ServiceReference1.ServiceResponce GetOrders(string machineName, KDSWPFClient.ServiceReference1.ClientDataFilter clientFilter) {
            return base.Channel.GetOrders(machineName, clientFilter);
        }
        
        public System.Threading.Tasks.Task<KDSWPFClient.ServiceReference1.ServiceResponce> GetOrdersAsync(string machineName, KDSWPFClient.ServiceReference1.ClientDataFilter clientFilter) {
            return base.Channel.GetOrdersAsync(machineName, clientFilter);
        }
        
        public System.Collections.Generic.Dictionary<string, object> GetHostAppSettings(string machineName) {
            return base.Channel.GetHostAppSettings(machineName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>> GetHostAppSettingsAsync(string machineName) {
            return base.Channel.GetHostAppSettingsAsync(machineName);
        }
        
        public void SetExpectedTakeValue(string machineName, int value) {
            base.Channel.SetExpectedTakeValue(machineName, value);
        }
        
        public System.Threading.Tasks.Task SetExpectedTakeValueAsync(string machineName, int value) {
            return base.Channel.SetExpectedTakeValueAsync(machineName, value);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKDSCommandService")]
    public interface IKDSCommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/LockOrder", ReplyAction="http://tempuri.org/IKDSCommandService/LockOrderResponse")]
        void LockOrder(string machineName, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/LockOrder", ReplyAction="http://tempuri.org/IKDSCommandService/LockOrderResponse")]
        System.Threading.Tasks.Task LockOrderAsync(string machineName, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/DelockOrder", ReplyAction="http://tempuri.org/IKDSCommandService/DelockOrderResponse")]
        void DelockOrder(string machineName, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/DelockOrder", ReplyAction="http://tempuri.org/IKDSCommandService/DelockOrderResponse")]
        System.Threading.Tasks.Task DelockOrderAsync(string machineName, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/LockDish", ReplyAction="http://tempuri.org/IKDSCommandService/LockDishResponse")]
        void LockDish(string machineName, int dishId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/LockDish", ReplyAction="http://tempuri.org/IKDSCommandService/LockDishResponse")]
        System.Threading.Tasks.Task LockDishAsync(string machineName, int dishId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/DelockDish", ReplyAction="http://tempuri.org/IKDSCommandService/DelockDishResponse")]
        void DelockDish(string machineName, int dishId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/DelockDish", ReplyAction="http://tempuri.org/IKDSCommandService/DelockDishResponse")]
        System.Threading.Tasks.Task DelockDishAsync(string machineName, int dishId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/ChangeOrderStatus", ReplyAction="http://tempuri.org/IKDSCommandService/ChangeOrderStatusResponse")]
        void ChangeOrderStatus(string machineName, int orderId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/ChangeOrderStatus", ReplyAction="http://tempuri.org/IKDSCommandService/ChangeOrderStatusResponse")]
        System.Threading.Tasks.Task ChangeOrderStatusAsync(string machineName, int orderId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/ChangeOrderDishStatus", ReplyAction="http://tempuri.org/IKDSCommandService/ChangeOrderDishStatusResponse")]
        void ChangeOrderDishStatus(string machineName, int orderId, int orderDishId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderDishStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKDSCommandService/ChangeOrderDishStatus", ReplyAction="http://tempuri.org/IKDSCommandService/ChangeOrderDishStatusResponse")]
        System.Threading.Tasks.Task ChangeOrderDishStatusAsync(string machineName, int orderId, int orderDishId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderDishStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKDSCommandServiceChannel : KDSWPFClient.ServiceReference1.IKDSCommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KDSCommandServiceClient : System.ServiceModel.ClientBase<KDSWPFClient.ServiceReference1.IKDSCommandService>, KDSWPFClient.ServiceReference1.IKDSCommandService {
        
        public KDSCommandServiceClient() {
        }
        
        public KDSCommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KDSCommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KDSCommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KDSCommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LockOrder(string machineName, int orderId) {
            base.Channel.LockOrder(machineName, orderId);
        }
        
        public System.Threading.Tasks.Task LockOrderAsync(string machineName, int orderId) {
            return base.Channel.LockOrderAsync(machineName, orderId);
        }
        
        public void DelockOrder(string machineName, int orderId) {
            base.Channel.DelockOrder(machineName, orderId);
        }
        
        public System.Threading.Tasks.Task DelockOrderAsync(string machineName, int orderId) {
            return base.Channel.DelockOrderAsync(machineName, orderId);
        }
        
        public void LockDish(string machineName, int dishId) {
            base.Channel.LockDish(machineName, dishId);
        }
        
        public System.Threading.Tasks.Task LockDishAsync(string machineName, int dishId) {
            return base.Channel.LockDishAsync(machineName, dishId);
        }
        
        public void DelockDish(string machineName, int dishId) {
            base.Channel.DelockDish(machineName, dishId);
        }
        
        public System.Threading.Tasks.Task DelockDishAsync(string machineName, int dishId) {
            return base.Channel.DelockDishAsync(machineName, dishId);
        }
        
        public void ChangeOrderStatus(string machineName, int orderId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderStatus) {
            base.Channel.ChangeOrderStatus(machineName, orderId, orderStatus);
        }
        
        public System.Threading.Tasks.Task ChangeOrderStatusAsync(string machineName, int orderId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderStatus) {
            return base.Channel.ChangeOrderStatusAsync(machineName, orderId, orderStatus);
        }
        
        public void ChangeOrderDishStatus(string machineName, int orderId, int orderDishId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderDishStatus) {
            base.Channel.ChangeOrderDishStatus(machineName, orderId, orderDishId, orderDishStatus);
        }
        
        public System.Threading.Tasks.Task ChangeOrderDishStatusAsync(string machineName, int orderId, int orderDishId, KDSWPFClient.ServiceReference1.OrderStatusEnum orderDishStatus) {
            return base.Channel.ChangeOrderDishStatusAsync(machineName, orderId, orderDishId, orderDishStatus);
        }
    }
}
